### ISSUE TITLE
Investigate REPLACEMENT_UNDERPRICED error

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker#144]
The following error was present in Airseeker:
```json
{
    "chainId": "31337",
    "code": "REPLACEMENT_UNDERPRICED",
    "dapiName": "0x4d415449432f5553440000000000000000000000000000000000000000000000",
    "dataFeedId": "0xc0dfaf62376fb61e522b28665c0053ff8822a3ffd13125622d8ed17df74a2e3f",
    "error": {
        "body": "{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n",
        "code": "SERVER_ERROR",
        "error": {
            "code": -32000
        },
        "reason": "processing response error",
        "requestBody": "{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f90514830138814c84861c469684861c4696830137ae949a0f9f6de89be3d155483a469a5feb2ee875fb5f80b904a4437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000c001a0af90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4da021157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748\"],\"id\":51,\"jsonrpc\":\"2.0\"}",
        "requestMethod": "POST",
        "url": "https://polygon-mumbai-bor.publicnode.com"
    },
    "level": "error",
    "message": "Failed to update a dAPI replacement fee too low [ See: https://links.ethers.org/v5-errors-REPLACEMENT_UNDERPRICED ] (error={\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":51,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}\\n\",\"error\":{\"code\":-32000},\"requestBody\":\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f90514830138814c84861c469684861c4696830137ae949a0f9f6de89be3d155483a469a5feb2ee875fb5f80b904a4437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000c001a0af90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4da021157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748\\\"],\\\"id\\\":51,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"https://polygon-mumbai-bor.publicnode.com\"}, method=\"sendTransaction\", transaction=\"0x02f90514830138814c84861c469684861c4696830137ae949a0f9f6de89be3d155483a469a5feb2ee875fb5f80b904a4437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000c001a0af90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4da021157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748\", code=REPLACEMENT_UNDERPRICED, version=providers/5.7.2)",
    "method": "sendTransaction",
    "ms": "+394ms",
    "providerName": "polygon-testnet",
    "reason": "replacement fee too low",
    "stack": "Error: replacement fee too low [ See: https://links.ethers.org/v5-errors-REPLACEMENT_UNDERPRICED ] (error={\"reason\":\"processing response error\",\"code\":\"SERVER_ERROR\",\"body\":\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":51,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}\\n\",\"error\":{\"code\":-32000},\"requestBody\":\"{\\\"method\\\":\\\"eth_sendRawTransaction\\\",\\\"params\\\":[\\\"0x02f90514830138814c84861c469684861c4696830137ae949a0f9f6de89be3d155483a469a5feb2ee875fb5f80b904a4437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000c001a0af90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4da021157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748\\\"],\\\"id\\\":51,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"url\":\"https://polygon-mumbai-bor.publicnode.com\"}, method=\"sendTransaction\", transaction=\"0x02f90514830138814c84861c469684861c4696830137ae949a0f9f6de89be3d155483a469a5feb2ee875fb5f80b904a4437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000c001a0af90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4da021157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748\", code=REPLACEMENT_UNDERPRICED, version=providers/5.7.2)\n    at Logger.makeError (/app/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/app/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at checkError (/app/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:160:16)\n    at StaticJsonRpcProvider.<anonymous> (/app/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)\n    at step (/app/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/app/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/app/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "timestamp": "2023-11-29T22:22:37.078Z",
    "transaction": {
        "accessList": [],
        "chainId": 80001,
        "confirmations": 0,
        "data": "0x437b9116000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003a000000000000000000000000000000000000000000000000000000000000001641a0a0b3e000000000000000000000000ac0653e412acae526da3a33af0135205a34e21af89bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b9a700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8eef8e4bab7d8800000000000000000000000000000000000000000000000000000000000000412780e58cfbc9296f850813df6947201155da5df9613518657728154d2aeda95c3b21c9c81bf7224c26861c750e9ff6a1e9f2b3165bbae8d2c1058da775e90dc91c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001641a0a0b3e0000000000000000000000002bf0ddda8daa1c3c0fae9e85866807a1c2d601b789bbdb4e2d7510abf1ca0ed53295e31c00a6939fc12e77d67bf3a4cb3c31f61c000000000000000000000000000000000000000000000000000000006567b96400000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000a8cba89636fea1c00000000000000000000000000000000000000000000000000000000000000415adec1a45072bf250742e47bc2f03848cd1c9068c35dc3f89a6a40a5f1add0f2504782f09b2a58e097d6f0fc4cb43cf9ae706baba11c36b286bf460f98de53131c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008400aae33f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000022c091c2a7346695ddb163560dc067b191358d7997225df254eaf0528ebbea165ceff9639ef2f7555a708bd9453e076d2f82c35f4ce364665d08879b1236624d500000000000000000000000000000000000000000000000000000000",
        "from": "0x7A43dAbc40FDd089276A3198909AbD2F798302B0",
        "gasLimit": {
            "hex": "0x0137ae",
            "type": "BigNumber"
        },
        "gasPrice": null,
        "hash": "0x53a0c1b1de3bd1036703d300dc63c905c3400e8882a54a53418183dd22e13e47",
        "maxFeePerGas": {
            "hex": "0x861c4696",
            "type": "BigNumber"
        },
        "maxPriorityFeePerGas": {
            "hex": "0x861c4696",
            "type": "BigNumber"
        },
        "nonce": 76,
        "r": "0xaf90af85ee55afc20aefc9805b9889ce2523302d800457cef97f8cd5173f2c4d",
        "s": "0x21157bf2d75d2bf8eef7cc2b94e4ed85dc2d4014cc0dd91df881222c925f5748",
        "to": "0x9A0F9f6dE89BE3D155483A469a5feB2eE875fB5F",
        "type": 2,
        "v": 1,
        "value": {
            "hex": "0x00",
            "type": "BigNumber"
        }
    },
    "transactionHash": "0x53a0c1b1de3bd1036703d300dc63c905c3400e8882a54a53418183dd22e13e47",
    "updateFeedsCoordinatorId": "1701296555802"
}
```

**Comment by Siegrift** [comment]
There was an update attempt 30 seconds before with same gas price:
```json
{
    "chainId": "31337",
    "dapiName": "0x4d415449432f5553440000000000000000000000000000000000000000000000",
    "dataFeedId": "0xc0dfaf62376fb61e522b28665c0053ff8822a3ffd13125622d8ed17df74a2e3f",
    "gasLimit": {
        "hex": "0x0137ae",
        "type": "BigNumber"
    },
    "gasPrice": {
        "hex": "0x861c4698",
        "type": "BigNumber"
    },
    "level": "debug",
    "message": "Updating dAPI",
    "ms": "+0ms",
    "providerName": "polygon-testnet",
    "timestamp": "2023-11-29T22:22:06.626Z",
    "updateFeedsCoordinatorId": "1701296525800"
}
```

I believe we should save not only the timestamp of the pending transaction, but also a gas price and only proceed with update if our recommended gas price is larger.

**Comment by Siegrift** [comment]
> I suppose the concern is the logs being noisy?

Yeah, I dislike having this error in the logs.

> I can imagine some edge cases where sending the transaction again with the same gas price is still beneficial. For example the provider has a load balancer in front, and has sent the second transaction to a different node with a different mempool that doesn't know about the first transaction.

We could do `gasPrice.add(1)` and use that just to make it slighlty larger an avoid that error?

**Comment by bbenligiray** [comment]
I think just parsing and ignoring this error is the better route
